name: CI/CD Pipeline with ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build the app
      run: mvn -B -DskipTests package --file pom.xml

    - name: Rename jar
      run: mv ./target/*.jar ./target/app.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

    - name: Checkout manifest repository
      uses: actions/checkout@v4
      with:
        repository: door-JH/app-with-argocd-img # <-- manifest 저장소
        token: ${{ secrets.TOKEN }}
        path: manifest-repo

    - name: Update Kubernetes manifest image tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}|" manifest-repo/manifest/argocd-deployment.yaml

    - name: Commit and push updated manifest
      run: |
        cd manifest-repo
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag to ${{ github.sha }}"
        git push origin main
